import { makeStyles } from "@material-ui/styles";

export const useStyles = makeStyles((theme) => ({
  root: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "#ECECEC",
    paddingBottom: "2rem",
    "& h2": {
      fontSize: "4rem",
      marginBottom: 0,
    },
    "& p": {
      width: "300px",
      textAlign: "center",
      fontSize: "0.9rem",
    },
  },
  blogContainer: {
    width: "1200px",
    height: "500px",
    position: "relative",
    margin: "2rem 0",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: "50%",
      transform: "translate(-50%)",
      height: "100%",
      width: "1px",
      border: "1px solid black",
    },
    // [theme.breakpoints.down("sm")]: {},
  },
  card: {
    width: "500px",
    display: "flex",
    "& img": {
      height: "50px",
    },
  },
  cardOne: {
    position: "absolute",
    top: 0,
    left: "7%",
    "&::before": {
      content: '""',
      position: "absolute",
      top: "50%",
      right: "-21px",
      height: "10px",
      width: "10px",
      borderRadius: "50%",
      background: "purple",
    },
  },
  cardTwo: {
    position: "absolute",
    top: "39%",
    right: 0,
    "&::before": {
      content: '""',
      position: "absolute",
      top: "50%",
      left: "-21%",
      height: "10px",
      width: "10px",
      borderRadius: "50%",
      background: "purple",
    },
  },
  cardThree: {
    position: "absolute",
    bottom: 0,
    left: "7%",
    "&::before": {
      content: '""',
      position: "absolute",
      top: "50%",
      right: "-21px",
      height: "10px",
      width: "10px",
      borderRadius: "50%",
      background: "purple",
    },
  },
  cardInfo: {
    marginLeft: ".5rem",
    "& h4": {
      fontSize: "1.1rem",
      margin: 0,
    },
  },
  content: {
    position: "relative",
    marginTop: "5px",
    marginLeft: "40px",
    "&::before": {
      content: '""',
      position: "absolute",
      top: "5px",
      left: "-40px",
      width: "36px",
      border: "1px solid black",
      background: "black",
    },
  },
  btn: {
    color: "#fff",
    backgroundColor: "purple",
    padding: "12px 30px",
    margin: "1.7rem 0",
    display: "inline-block",
    borderRadius: "6px",
    fontSize: "28px",
    width: "240px",
    textAlign: "center",
    "& span": {
      display: "inline-block",
      position: "relative",
      transition: "0.3s",
    },
    "& span svg": {
      position: "absolute",
      top: "20%",
      right: "-30px",
      opacity: 0,
      transition: "0.3s",
    },
    "&:hover": {
      cursor: "pointer",
    },
    "&:hover span": {
      paddingRight: "30px",
    },
    "&:hover span svg": {
      right: 0,
      opacity: 1,
    },
  },
}));
